### PR TITLE
Update example.tex

### PR DESCRIPTION
**Pull request by ghost**
line 35: \bss changed with \lds

### CODE REVIEW

**Comment by bozsahin** [comment]
Ozan is there something wrong with \bss?

**Comment by ghost** [comment]
Hocam, when I run the code it gives this error " line38:Undefined control sequence. } " and double slash is not shown .Then I checked ccg-latex.sty. I cant see \bss command. When I changed it to \lds, the problem is fixed.

**Comment by bozsahin** [comment]
that needs fixing in ccg-latex.sty, not in example.tex. 

added the aliases. let me know if they don't work
c

**Comment by ghost** [comment]
Now it works.

**Comment by bozsahin** [comment]
problem dealt with in ccg-latex.sty. thanks Ozan.
c

**Pull request closed without merging**
